# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: miyucomics
book_id: hexical:hexicalbook
default_branch: main
github_repo: hexical
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexicalModPlugin
hexdoc_plugin_classname: HexicalPlugin
java_lang:
    ext: java
    src: java
java_package: miyucomics/hexical
mod_display_name: Hexical
modid: hexical
multiloader: true
package_export_root: doc/src/hexdoc_hexical/_export
package_name: hexdoc-hexical
package_slug: hexdoc_hexical
package_src: doc/src/hexdoc_hexical
pages_url: https://miyucomics.github.io/hexical
pattern_regex:
    per_world_value: registerPerWorld
    regex: (?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?
pattern_registry: registry/HexicalPatternRegistry.java
