# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.0.5
_src_path: gh:FallingColors/hexdummy
author: miyucomics
capitalize_platforms: false
classname: Hexical
default_branch: main
description: A kitchen sink addon for Hexcasting
display_name: Hexical
github_repo: hexical
hexcasting_version: 0.10.3
homepage_url: https://miyucomics.github.io/hexical
initial_mod_version: 0.0.1
java_version: 17
license: MIT
mappings_name: Yarn
modid: hexical
package: miyucomics.hexical
sources_url: https://github.com/miyucomics/hexical
