author: miyucomics
book_id: "hexical:hexicalbook"
default_branch: main
github_repo: hexical
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexicalModPlugin
hexdoc_plugin_classname: HexicalPlugin
java_lang:
  ext: java
  src: java
java_package: miyucomics/hexical
mod_display_name: Hexical
modid: hexical
multiloader: true
pages_url: https://miyucomics.github.io/hexical
pattern_regex:
  regex: '(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?'
  per_world_value: registerPerWorld
pattern_registry: registry/HexicalPatternRegistry.java
