modid = "hexical"
book = "hexical:hexicalbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [
    "resources",
    "{_common.src}/main/resources",
    { path = "{^_common.src}/generated/resources", required = false },
    "{_fabric.src}/main/resources",
    { path = "{^_fabric.src}/generated/resources", required = false },
    "{_forge.src}/main/resources",
    { path = "{^_forge.src}/generated/resources", required = false },
    { modid = "hexcasting" },
    { modid = "minecraft" },
    { modid = "hexdoc" },
]
export_dir = "src/hexdoc_hexical/_export/generated"

[template]
icon = "icon.png"
include = [
    "hexical",
    "hexcasting",
    "hexdoc"
]

[template.args]
mod_name = "Hexical"
author = "miyucomics"
show_landing_text = false

[extra.hexcasting]
_pattern_regex = { "!Raw" = '(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?' }
_per_world_value = "registerPerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/registry/HexicalPatterns.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

[_common]
src = "../common/src"
package = "{src}/main/java/miyucomics/hexical"

[_fabric]
src = "../fabric/src"
package = "{src}/main/java/miyucomics/hexical/fabric"

[_forge]
src = "../forge/src"
package = "{src}/main/java/miyucomics/hexical/forge"